image: python:3.6.5
variables:
    S3_BUCKET: demo-20200925-spf
    AWS_DEFAULT_REGION: ap-northeast-1
stages:
    - test
    - deploy
unittest:
    stage: test    
    script:
        - pip install pytest pytest-mock mocker moto
        - pip install -r requirements.txt
        - python -m pytest tests/ -v
deploy:
    stage: deploy
    script:
        - pip install awscli
        - pip install -r requirements.txt -t hello_world/build/
        - cp hello_world/*.py hello_world/build/
        - aws cloudformation package --template-file template.yaml --output-template-file output.yaml  --s3-bucket ${S3_BUCKET}
        - aws cloudformation deploy --template-file output.yaml --stack-name demo --capabilities CAPABILITY_IAM